services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: phillydb-web
    env: docker # valid values: https://render.com/docs/yaml-spec#environment
    dockerfilePath: Dockerfile
    domains: # custom domains
      - "www.whoownsphilly.org"
    envVars:
      - key: BIOS_URL # Imported from Heroku app
        value: https://api.airtable.com/v0/appWtLiq9Ezlbp7s1/Visible%20On%20Website%20-%20By%20Mailing%20Address?api_key&#x3D;keyygo7ozRiqZGwWa
      - key: DJANGO_DEBUG # Imported from Heroku app
        value: false
      - key: MEMCACHIER_SERVERS # Imported from Heroku app
        value: mc4.dev.ec2.memcachier.com:11211
      - key: MEMCACHIER_USERNAME # Imported from Heroku app
        value: AB44B0
